apiVersion: apps/v1
kind: Deployment
metadata:
  name: hvac-controller-deployment
  namespace: grp02eq5-namespace
  labels:
    app: hvac-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hvac-controller
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      name: hvac-controller-deployment
      labels:
        app: hvac-controller
    spec:
      containers:
      - name: hvac-controller
        image: raphdup/oxygencs-grp2-eq5:latest
        imagePullPolicy: Always
        env:
          - name: HVAC_HOST
            valueFrom:
              configMapKeyRef:
                name: hvac-controller-config
                key: HVAC_HOST_KEY
          - name: TOKEN
            valueFrom:
              configMapKeyRef:
                name: hvac-controller-config
                key: token
          - name: T_MIN
            valueFrom:
              configMapKeyRef:
                name: hvac-controller-config
                key: T_MIN
          - name: T_MAX
            valueFrom:
              configMapKeyRef:
                name: hvac-controller-config
                key: T_MAX
        resources:
          limits:
            memory: "128Mi"
            cpu: "50m"
          requests:
            memory: "64Mi"
            cpu: "50m"
      restartPolicy: Always
